name: Netlify

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        if: github.event.pull_request.merged == true

      - name: Setup Node.js 10.x
        uses: actions/checkout@v2
        with:
          node-version: "10.x"
        if: github.event.pull_request.merged == true

      - name: Setup Hexo
        run: npm install hexo --save
        if: github.event.pull_request.merged == true

      - name: Setup Netlify Cli
        run: npm install netlify-cli --save
        if: github.event.pull_request.merged == true

      - name: Build
        run: npx hexo generate
        if: github.event.pull_request.merged == true

      - name: Build
        run: npx hexo generate
        if: github.event.pull_request.merged == true

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --dir=./public
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
